# https://pre-commit.com/
default_language_version:
    python: python3.8
exclude: ^botkit/utils/legacy
repos:
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: ["--count", "--select=E9,F63,F7", "--show-source", "--statistics", "--max-complexity=10", "--max-line-length=127"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    -   id: mypy
        files: ^telegram/.*\.py$
